const language = {
  en: {
    english: "English",
    arabic: "Arabic",
    companyTitle: "We are The EgyVista Company",
    companyParagraph:
      "With EgyVista, feel the spirit of Egypt — its history, sun, and sea.",
    discover: "Discover",
    exploreNow: "Explore Now",
    about: "About",
    services: "Services",
    portfolio: "Portfolio",
    preview: "Preview",
    footer: "Footer",
    tourType: "Tour Type",
    ancientEgypt: "Ancient Egypt",
    beaches: "Beaches",
    curise: "Curise",
    hiking: "Hiking",
    beaches: "Beaches",
    islamic: "Islamic",
    curise: "Curise",
    hiking: "Hiking",
    museums: "Museums",
    camping: "Camping",
    topDestination: "Top Destination",
    bookParagraph1: "Plan Your Trip with Us",
    bookParagraph2: "Ready for an unforgetable tour?",
    book: "Book Now",
    cairo: "Cairo",
    hurghada: "Hurghada",
    fayoum: "Fayoum",
    luxor: "Luxor",
    sharm: "Sharm el Sheikh",
    giza: "giza",
    aswan: "Aswan",
    marsaAlam: "Marsa Alam",
    saint: "Saint Catherine's Monastery",
    topAttractions: "Top Attractions",
    ancientPlaces: "Ancient Places",
    warmDestinations: "Warm Destinations",
    price: "Price",
    contact: "Contact Us",
    faq: "FAQ",
    feature: "Featured",
  },
  ar: {
    english: "الأنجليزية",
    arabic: "العربية",
    discover: "أستكشف",
    companyTitle: "نحن شركه EgyVista",
    companyParagraph: "مع EgyVista عش سحر مصر بين التاريخ، والشمس، والبحر",
    exploreNow: "أستكشف الآن",
    about: "من نحن",
    services: "الخدمات",
    portfolio: "الموقع الشخصى",
    preview: "مراجعة",
    footer: "الخاتمة",
    tourType: "أنواع الرحلات",
    ancientEgypt: "مصر القديمة",
    beaches: "الشواطئ",
    curise: "رحلة نهرية",
    hiking: "التسلق",
    beaches: "الشواطئ",
    islamic: "إسلامى",
    curise: "رحلة نهرية",
    hiking: "التسلق",
    museums: "المتاحف",
    camping: "التخييم",
    topDestination: "أفضل المدن",
    bookParagraph1: "خطط لرحلتك معنا الان",
    bookParagraph2: "هل أنت مستعد لرحلة لا تنسى؟",
    book: "أحجز الآن",
    cairo: "القاهرة",
    hurghada: "الغردقة",
    fayoum: "الفيوم",
    luxor: "الأقصر",
    sharm: "شرم الشيخ",
    giza: "الجيزة",
    aswan: "أسوان",
    marsaAlam: "مرسى علم",
    saint: "قلعة سانت كاترين",
    topAttractions: "مناطق الجذب السياحى",
    ancientPlaces: "المناطق الأثرية",
    warmDestinations: "المناطق الساحلية",
    price: "السعر",
    contact: "تواصل معنا",
    faq: "الأسئلة الشائعة",
    feature: "مميزة",
  },
};

export { language };
